[package]
name = "quite-water"
version = "0.1.0"
edition = "2024"

[dependencies]
whisper-rs = { version = "0.16.0"}
hound = "3.5.1"
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"] }
rig = "0.42.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0"